export default {
    INITIAL_SCREEN:"initialScreen",
    LOGIN:"login",
    SIGNUP:"signup",
    HOME:"home",
    SEARCH:"search",
    CREATE_POST:"createPost",
    PROFILE:"profile",
    NOTIFICATION:"notification",
    TAB_ROUTES:"tabRouts",
    OTP_VERIFICATION:"otpVerification",
    WEBVIEW:"webView",
    PORFILE_EDIT:"profileEdit",
    LINKS:"links",
    ADD_POST:"addPost",
    POST_DETAIL:"postDetail",
    CHATS:"chats",
    MESSAGES:"Messages"
}